In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split, cross_val_score, KFold, GridSearchCV 
from sklearn.metrics import confusion_matrix, accuracy_score
import pandas as pd
import numpy as np

In [3]:
iris = datasets.load_iris()
digits = datasets.load_digits()

In [4]:
X, Y = iris.data, iris.target

In [5]:
from sklearn.tree import DecisionTreeClassifier,export_graphviz

In [6]:
train_X,test_X,train_Y,test_Y =train_test_split(X,Y,test_size=0.2,
                                                random_state=123)

In [7]:
decisiontree = DecisionTreeClassifier(random_state = 123)
decisiontree.fit(train_X, train_Y)
dtpred = decisiontree.predict(train_X)
# dtpred = decisiontree.predict(train_X)

In [8]:
decisiontree.score(test_X, test_Y)

0.9666666666666667

In [9]:
decisiontree.predict([[5.0, 4.0, 6.5, 2.0]])

array([2])

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
logreg = LogisticRegression(random_state = 123)
logreg.fit(train_X, train_Y)
# logregpred = logreg.predict(test_X)
logregpred = logreg.predict(train_X)

In [12]:
logreg.score(test_X, test_Y)

1.0

In [13]:
logreg.predict([[5.0, 4.0, 6.5, 2.0]])

array([2])

In [14]:
from sklearn.svm import SVC

In [15]:
clf = SVC()
clf.fit(train_X, train_Y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
pred_svm=clf.predict(train_X)

In [17]:
clf.score(test_X, test_Y)

0.9666666666666667

In [18]:
clf.predict([[5.0, 4.0, 6.5, 2.0]])

array([2])

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(train_X, train_Y) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [21]:
pred_knn=knn.predict(train_X)

In [22]:
knn.score(test_X, test_Y)

0.9666666666666667

In [23]:
knn.predict([[5.0, 4.0, 6.5, 2.0]])

array([2])

## Confussion Matrix

In [25]:
cm = confusion_matrix(train_Y,logregpred)

total=sum(sum(cm))
accuracy = (cm[0,0]+cm[1,1])/total
sensitivity = cm[1,1]/(cm[1,0]+cm[1,1])
specificity = cm[0,0]/(cm[0,0]+cm[0,1])

print('Confusion Matrix : \n', cm)
print('Accuracy : ', accuracy)
print('Sensitivity : ', sensitivity)
print('Specificity : ', specificity)

Confusion Matrix : 
 [[37  0  0]
 [ 0 40  4]
 [ 0  1 38]]
Accuracy :  0.6416666666666667
Sensitivity :  1.0
Specificity :  1.0
