In [2]:
import numpy as np

In [30]:
A = [[2, -1, 2], [-2, 3, -4], [1, -1, 3]]
diag = [[6,0,0], [0,1,0], [0,0,1]]
B = np.transpose(A)
e_val, e_vec = np.linalg.eig(B)
print(e_vec)
print(e_val)
print(B)
# print()
# print(e_vec)
tes = np.dot(e_vec, np.transpose(diag))
np.dot(tes, np.linalg.inv(e_vec))

[[-0.40824829 -0.50222833  0.86820728]
 [ 0.40824829  0.17255747  0.48545624]
 [-0.81649658  0.84734327  0.10270521]]
[6. 1. 1.]
[[ 2 -2  1]
 [-1  3 -1]
 [ 2 -4  3]]


array([[ 2., -2.,  1.],
       [-1.,  3., -1.],
       [ 2., -4.,  3.]])

In [34]:
e_v = np.array([[2,-1,1], [1,0,-1], [0,1,2]])
diag2 = [[1,0,0], [0,1,0], [0,0,6]]
inv_e = np.linalg.inv(e_v)
u = np.dot(diag2, inv_e)
print(inv_e)
print(np.dot(e_v, u))

[[ 0.2  0.6  0.2]
 [-0.4  0.8  0.6]
 [ 0.2 -0.4  0.2]]
[[ 2. -2.  1.]
 [-1.  3. -1.]
 [ 2. -4.  3.]]
